Hw jv dao6
RuslanIbIsh/jv-dao3 pull request #4
Opened 2021-01-16 19:32 UTC by RuslanIbIsh

2021-01-16 21:52 UTC, Ilya-brinchuk requested changes

2021-01-16 21:52 UTC, Ilya-brinchuk commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
А водителей ты при создании не добавляешь,

2021-01-16 21:52 UTC, Ilya-brinchuk commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            return preparedStatement.executeUpdate() > 0;
А водителей из машины ты не удаляешь?

2021-01-16 21:52 UTC, Ilya-brinchuk commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            Driver driver = null;
Помоему ты нигде это не используешь

2021-01-16 21:52 UTC, Ilya-brinchuk commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +        return Optional.empty();
От этого Optional.empty можно избавиться если использовать for вместо while

2021-01-16 21:55 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
The car has an empty list of drivers when being written to database

2021-01-16 21:56 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            return preparedStatement.executeUpdate() > 0;
There is no need to delete all links from cars_drivers table, because when reading from DB, we will write ...AND deleted = false, which will avoid reading these links

2021-01-16 22:29 UTC, IvanLuchkin requested changes

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't insert car in method create", e);
Adding a `car.toString()` representation to the message would be more informative

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted != TRUE AND m.deleted !=TRUE AND c.id = ? ";
I wouldn't recommend adding an manufacturers.deleted check because in such case you won't be able to retrieve cars, whose manufacturers are deleted. Even if we get a car with deleted manufacturer, we can check this manufacturer later and I think it will not be updated anyway, it will stay deleted

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        ) {
I would move the closing brace to the previous line

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted != TRUE AND m.deleted !=TRUE AND c.id = ? ";
Also, changing `c.deleted != true` to `c.deleted = false` would be better for readability

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            return Optional.of(car);
```suggestion
            return Optional.ofNullable(car);
```
`Optional.of()` will throw NPE if car is not found, null-check should be handled by the service

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
We can do this in one loop by introducing a `Car` variable and setting it's drivers right away. Also, comments from `get()` method are relevant here

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't fetch cars in method getAll", e);
```suggestion
            throw new DataProcessingException("Could not get all cars", e);
```

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    public void removeDriverFromCar(Driver driver, Car car) {
Isn't it a service method? In the service, we can do all the necessary manipulations with the car and just run update()

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    public void removeDriverFromCar(Driver driver, Car car) {
I would move `deleteQuery` for cars_drivers table to `update()` and get rid of the extra method. Moreover, this method has it's own connection, which is not provided by the caller method (update). This will be very slow in terms if performance.

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't execute getAllByDriver in CarDaoImpl", e);
```suggestion
            throw new DataProcessingException("Could not get all cars by driver with id " + driverId, e);
```
We should avoid class names in exception messages since they don't provide relevant information

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    }
We can move this logic to `update()` method and remove any confusion with similar method names; this method is used only once in your code, which is a great signal that we don't really need this logic to be separated

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        String manufacturerCountry = resultSet.getNString("manufacturer_country");
Why `getNString()`?

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        return Optional.of(driver);
I think that returning `Optional` right after calling a constructor is really redundant, since `driver` cannot be `null` by default

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        return Optional.of(driver);
Extra wrapper, then extra `get()` call, it will slow your program down

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +        return Optional.empty();
```suggestion
        return Optional.ofNullable(driver);
```

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't receive driver in method get", e);
```suggestion
            throw new DataProcessingException("Could not get driver by id " + id, e);
```
You get the point, check you other methods))

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't get connection in method getAll", e);
The problem may not be in retrieving the connection, I would write a more generalized message

2021-01-16 22:29 UTC, IvanLuchkin commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +        throw new DataProcessingException("Can't update driver");
Should we throw an exception if nothing has been updated?

2021-01-17 13:18 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
ok

2021-01-17 13:19 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            return preparedStatement.executeUpdate() > 0;
не нужно

2021-01-17 13:26 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            Driver driver = null;
уже юзаю)

2021-01-17 13:26 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +        return Optional.empty();
переписал

2021-01-17 14:59 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't insert car in method create", e);
ok

2021-01-17 15:01 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted != TRUE AND m.deleted !=TRUE AND c.id = ? ";
ok

2021-01-17 15:03 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        ) {
ok

2021-01-17 15:05 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            return Optional.of(car);
ok

2021-01-17 15:07 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
Let's see

2021-01-17 15:09 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't fetch cars in method getAll", e);
ok

2021-01-17 15:10 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    public void removeDriverFromCar(Driver driver, Car car) {
Let's leave in separate methods

2021-01-17 15:12 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            throw new DataProcessingException("Can't execute getAllByDriver in CarDaoImpl", e);
ok

2021-01-17 15:25 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    }
Let's leave

2021-01-17 15:26 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        String manufacturerCountry = resultSet.getNString("manufacturer_country");
more saifty method

2021-01-17 15:31 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        return Optional.of(driver);
ok

2021-01-17 15:33 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't receive driver in method get", e);
ok

2021-01-17 15:34 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't get connection in method getAll", e);
ok

2021-01-17 15:35 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +        throw new DataProcessingException("Can't update driver");
driver is unreachable

2021-01-18 14:05 UTC, Ilya-brinchuk approved these changes

2021-01-18 17:26 UTC, KseniiaMakarova requested changes

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/Application.java
> +        driverService.update(updatedDriver);
```suggestion
        Driver updatedDriverOne = driverService.get(driverOne.getId());
        updatedDriverOne.setName("new name");
        driverService.update(updatedDriverOne);
```
this is a more appropriate use of update() method

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/CarDao.java
> +    void addDriverToCar(Driver driver, Car car);
we should not have this method on dao level, only on service level

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/CarDao.java
> +    void removeDriverFromCar(Driver driver, Car car);
same

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/service/impl/CarServiceImpl.java
> +        carDao.addDriverToCar(driver, car);
let's not change this class

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +;
add empty line

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            while (resultSet.next()) {
```suggestion
            if (resultSet.next()) {
```

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +
redundant empty line

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            car.setDrivers(getAllDriversByCar(car));
let's not open another connection inside this one - move this line below the catch block

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
same here

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
same here

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    public void addDriverToCar(Driver driver, Car car) {
here we open many connections and statements because we use a loop
let's open them once and then inside the try block just execute the statement for each driver
```suggestion 
    private void addDriverToCar(Car car) {
```

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    private Optional<Car> constructCarFromResultSet(ResultSet resultSet) throws SQLException {
let's return Car here, not Optional
we will have the car for sure

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    private Optional<Driver> constructDriverFromResultSet(ResultSet resultSet)
same here

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted != TRUE AND d.deleted != TRUE AND m.deleted != TRUE";
```suggestion
                + "WHERE c.deleted = FALSE AND d.deleted = FALSE AND m.deleted = FALSE";
```
and what about driver id?

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
move this out of the try block

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "d.license_number as license_number "
do you need aliases here?

2021-01-18 17:26 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE cd.car_id = ? AND d.deleted != TRUE";
```suggestion
                + "WHERE cd.car_id = ? AND d.deleted = FALSE";
```

2021-01-18 17:40 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/Application.java
> +        driverService.update(updatedDriver);
done

2021-01-18 17:41 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/CarDao.java
> +    void addDriverToCar(Driver driver, Car car);
done

2021-01-18 17:41 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/CarDao.java
> +    void removeDriverFromCar(Driver driver, Car car);
done

2021-01-18 17:43 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/service/impl/CarServiceImpl.java
> +        carDao.addDriverToCar(driver, car);
done

2021-01-18 17:45 UTC, RuslanIbIsh commented on src/main/resources/init_db.sql
> +;
done

2021-01-18 17:45 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            while (resultSet.next()) {
done

2021-01-18 17:47 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +
done

2021-01-18 17:52 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            car.setDrivers(getAllDriversByCar(car));
done

2021-01-18 17:54 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
done

2021-01-18 17:55 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
done

2021-01-18 18:00 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    public void addDriverToCar(Driver driver, Car car) {
done

2021-01-18 18:02 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    private Optional<Car> constructCarFromResultSet(ResultSet resultSet) throws SQLException {
done

2021-01-18 18:02 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +    private Optional<Driver> constructDriverFromResultSet(ResultSet resultSet)
done

2021-01-18 18:04 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted != TRUE AND d.deleted != TRUE AND m.deleted != TRUE";
done

2021-01-18 18:04 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted != TRUE AND d.deleted != TRUE AND m.deleted != TRUE";
done

2021-01-18 18:06 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +            }
done

2021-01-18 18:07 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "d.license_number as license_number "
done

2021-01-19 07:32 UTC, KseniiaMakarova requested changes

2021-01-19 07:32 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't get connection in method create Driver", e);
```suggestion
            throw new DataProcessingException("Can't create Driver", e);
```
I would recommend to make these messages (in all the methods more general - we can have different SQLException, not only relating to the connection)

2021-01-19 07:32 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        car.setDrivers(getAllDriversByCar(car));
let's do this if the car is not null - otherwise we might get NPE in getAllDriversByCar() method

2021-01-19 07:32 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE id = ? AND deleted != TRUE";
```suggestion
                + "WHERE id = ? AND deleted = false";
```

2021-01-19 07:32 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted = false AND d.deleted = false AND m.deleted = false ";
and where cd.driver_id = ?

2021-01-19 07:40 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't get connection in method create Driver", e);
done

2021-01-19 07:41 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +        car.setDrivers(getAllDriversByCar(car));
done

2021-01-19 07:41 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE id = ? AND deleted != TRUE";
done

2021-01-19 07:47 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE id = ? AND deleted != TRUE";
done

2021-01-19 07:48 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/CarDaoImpl.java
> +                + "WHERE c.deleted = false AND d.deleted = false AND m.deleted = false ";
done

2021-01-19 09:59 UTC, KseniiaMakarova approved these changes

2021-01-19 09:59 UTC, KseniiaMakarova commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't create Driver", e);
let's also review other messages in DriverDaoImpl class

2021-01-19 10:18 UTC, RuslanIbIsh commented on src/main/java/com/iri/dao3/dao/jdbc/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't create Driver", e);
I wrote more specified and informativ messages in methods in DriverDaoImpl

2021-01-19 11:11 UTC, merged